CREATE DATABASE IF NOT EXISTS `${DB_NAME}` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE USER IF NOT EXISTS `${DB_USER}` @'%' IDENTIFIED BY '${DB_PASS}';

GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO `${DB_USER}` @'%';

FLUSH PRIVILEGES;