   RewriteEngine On

    RewriteRule "(\/vendor\/)" - [L,R=404]
    RewriteRule "(\/node_modules\/)" - [L,R=404]
    RewriteRule "(^|/)\.(?!well-known\/)" - [L,R=404]
    RewriteRule "(composer\.json)" - [L,R=404]
    RewriteRule "(\.lock)" - [L,R=404]
    RewriteRule "(\/environment.xml)" - [L,R=404]
    RewriteRule "(\/lib\/classes)" - [L,R=404]
    RewriteRule "(\/install.xml)" - [L,R=404]
    RewriteRule "(\/README)" - [L,R=404]
    RewriteRule "(\/readme)" - [L,R=404]
    RewriteRule "(\/moodle_readme)" - [L,R=404]
    RewriteRule "(\/upgrade\.txt)" - [L,R=404]
    RewriteRule "(phpunit\.xml\.dist)" - [L,R=404]
    RewriteRule "(\/tests\/behat\/)" - [L,R=404]
    RewriteRule "(\/fixtures\/)" - [L,R=404]
    RewriteRule "(\/upgrade\.txt|UPGRADING\.md|UPGRADING\-CURRENT\.md)" - [L,R=404]