# Definir un VirtualHost que escucha en todos los interfaces en el puerto 80 (HTTP)
<VirtualHost *:${SERVER_PORT}>
    # Nombre del servidor (se sustituye con la variable de entorno MOODLE_SERVER_NAME)
    ServerName ${SERVER_NAME}
    # Email del administrador del servidor
    ServerAdmin you@${SERVER_NAME}

    # Directorio raíz donde se encuentran los archivos de la aplicación
    DocumentRoot "${SERVER_ROOT_PATH}/public"
    # Configuración del directorio raíz
    <Directory "${SERVER_ROOT_PATH}/public">
        # Permitir listar índices y seguir enlaces simbólicos
        Options Indexes FollowSymLinks
        # Permitir sobrescribir configuración con archivos .htaccess
        AllowOverride None
        # Permitir acceso a todos
        Require all granted
        # Denegar acceso a archivos de configuración y control de versiones
        <FilesMatch "^\.(htaccess|htpasswd|ini|php|git)$">
            Require all denied
        </FilesMatch>
        RewriteEngine On

        RewriteRule "(\/vendor\/)" - [L,R=404]
        RewriteRule "(\/node_modules\/)" - [L,R=404]
        RewriteRule "(^|/)\.(?!well-known\/)" - [L,R=404]
        RewriteRule "(composer\.json)" - [L,R=404]
        RewriteRule "(\.lock)" - [L,R=404]
        RewriteRule "(\/environment.xml)" - [L,R=404]
        RewriteRule "(\/lib\/classes)" - [L,R=404]
        RewriteRule "(\/install.xml)" - [L,R=404]
        RewriteRule "(\/README)" - [L,R=404]
        RewriteRule "(\/readme)" - [L,R=404]
        RewriteRule "(\/moodle_readme)" - [L,R=404]
        RewriteRule "(\/upgrade\.txt)" - [L,R=404]
        RewriteRule "(phpunit\.xml\.dist)" - [L,R=404]
        RewriteRule "(\/tests\/behat\/)" - [L,R=404]
        RewriteRule "(\/fixtures\/)" - [L,R=404]
        RewriteRule "(\/upgrade\.txt|UPGRADING\.md|UPGRADING\-CURRENT\.md)" - [L,R=404]
    </Directory>

    # Archivos índice por defecto (en orden de prioridad)
    DirectoryIndex info.php index.php index.html 
        
    # Archivo de registro de errores
    ErrorLog /var/log/apache2/error_${SERVER_NAME}.log 
    # Archivo de registro de acceso
    CustomLog /var/log/apache2/access_${SERVER_NAME}.log combined
# Cierre de la configuración del VirtualHost
</VirtualHost>

