# Asegúrate de ajustar la ruta absoluta si no usas variables de entorno de Apache
Alias "${ALIAS_INFO_PATH}" "${SERVER_INFO_PATH}/php-info.php"

# Otorgar permisos de acceso al archivo si es necesario
<Files "php-info.php">
    Require all granted
</Files>