[PHP]

display_errors = Off
display_startup_errors = Off

; Registrar errores
log_errors = On
error_log = /var/log/php/error.log

; Nivel de reporte
error_reporting = E_ALL

; Tamaño máximo del log
log_errors_max_len = 0


upload_max_filesize = 100M
post_max_size = 100M
max_file_uploads = 50

max_execution_time = 300
max_input_time = 300
memory_limit = 512M

session.save_handler = files
session.save_path = "/var/lib/php/session"
session.use_strict_mode = 1
session.gc_maxlifetime = 1440
session.cookie_httponly = 1
session.use_only_cookies = 1

extension = intl
extension = xml
extension = xmlreader
extension = xmlwriter
extension = soap
extension = dom
extension = simplexml
extension = curl
extension = openssl
extension = json
extension = mbstring
extension = tokenizer
extension = ctype
extension = zip
extension = gd
extension = fileinfo
extension = exif
extension = sodium
extension = pdo
extension = pdo_mysql
extension = mysqli

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
opcache.fast_shutdown = 1

error_log = /var/log/php/php-error.log

cli_server.color = On
