FROM alpine:latest

ARG APP_LOCAL_HTTPCONF_PATH
ARG APP_SERVER_HTTPCONF_PATH
ARG APP_LOCAL_HTTPCONFD_PATH
ARG APP_SERVER_HTTPCONFD_PATH
ARG APP_LOCAL_ENTRYPOINT_PATH
ARG APP_SERVER_ENTRYPOINT_PATH

RUN apk update && apk upgrade && \
    apk --no-cache add apache2 apache2-utils apache2-proxy curl

COPY ${APP_LOCAL_HTTPCONF_PATH} ${APP_SERVER_HTTPCONF_PATH}
COPY ${APP_LOCAL_HTTPCONFD_PATH}/*.conf ${APP_SERVER_HTTPCONFD_PATH}/

# Script de entrada para expandir variables
COPY ${APP_LOCAL_ENTRYPOINT_PATH} ${APP_SERVER_ENTRYPOINT_PATH}
RUN chmod +x ${APP_SERVER_ENTRYPOINT_PATH}

ENTRYPOINT ["sh", "/entrypoint.sh"]